port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7893
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: folder
interface-name: en0
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - tcp://1.1.1.1
    - tcp://8.8.8.8
  fallback:
    - 1.0.0.1
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
    - 112.215.37.165
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 112.215.37.165
proxy-groups:
- name: FINAL
  type: select
  proxies:
  - SG ðŸ‡¸ðŸ‡¬
  - ID ðŸ‡®ðŸ‡©
  - BestPing âœ¨
  - LoadSG ðŸ‡¸ðŸ‡¬
  - LoadID ðŸ‡®ðŸ‡©
  - BestPingSG
  - BestPingID
- name: ID ðŸ‡®ðŸ‡©
  type: select
  use:
  - id
- name: SG ðŸ‡¸ðŸ‡¬
  type: select
  use:
  - sg
- name: BestPing âœ¨
  type: url-test
  tolerance: 100
  use:
  - BestPingSG
  - BestPingID
- name: BestPingSG 
  type: url-test
  tolerance: 100
  use:
  - sg
- name: BestPingID
  type: url-test
  tolerance: 100
  use:
  - id
- name: LoadSG ðŸ‡¸ðŸ‡¬
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - sg
- name: LoadID ðŸ‡®ðŸ‡©
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - id

proxy-providers:
  sg:
    type: file
    path: ./sg.yaml
    url: https://raw.githubusercontent.com/Lolyodd/lolyodd.github.io/master/config/proxy/sg.yaml
    health-check:
      enable: true
      interval: 300
      lazy: true
      url: 'http://www.gstatic.com/generate_204'
      
  id:
    type: file
    path: ./id.yaml
    url: https://raw.githubusercontent.com/Lolyodd/lolyodd.github.io/master/config/proxy/id.yaml
    health-check:
      enable: true
      interval: 300
      lazy: true
      url: 'http://www.gstatic.com/generate_204'

rules:

  - PROCESS-NAME,com.facebook.lite,SG ðŸ‡¸ðŸ‡¬
  - PROCESS-NAME,com.kiwibrowser.browser,SG ðŸ‡¸ðŸ‡¬
  - PROCESS-NAME,com.google.android.youtube,LoadSG ðŸ‡¸ðŸ‡¬
  - PROCESS-NAME,id.dana,ID ðŸ‡®ðŸ‡©
  - PROCESS-NAME,com.whatsapp,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - IP-CIDR6,fc00::/7,DIRECT,no-resolve
  - IP-CIDR6,fe80::/10,DIRECT,no-resolve
  - IP-CIDR6,fd00::/8,DIRECT,no-resolve
  - SRC-IP-CIDR,192.168.1.201/32,DIRECT
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - GEOIP,IR,DIRECT

  - IP-CIDR,127.0.0.0/8,DIRECT
  - GEOIP,CN,DIRECT
  - DST-PORT,80,DIRECT
  - SRC-PORT,7777,DIRECT
  - MATCH,FINAL
